# Copyright 2017 The Fuchsia Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: xi_flutter
description: Vanilla Flutter Xi UI
dependencies:
  flutter:
    sdk: flutter
  path: 1.4.1
  xi_widgets:
    path: ../packages/widgets
  xi_client:
    path: ../packages/xi_client
flutter:
  uses-material-design: true
